# yaml-language-server: $schema=schema/buf.bufstream.config.v1alpha1.BufstreamConfig.schema.json
data_enforcement:
  schema_registries:
    - name: csr
      confluent:
        url: "https://demo.buf.dev/integrations/confluent/bufstream-demo"
        instance_name: "bufstream-demo"
  # This is applied when records are sent to Bufstream.
  produce:
    - schema_registry: csr
      values:
        # If a record is not enveloped, automatically envelope it.
        coerce: true
        # If a record cannot be parsed, reject all records in the batch.
        on_parse_error: REJECT_BATCH
        # If a schema cannot be found, reject all records in the batch.
        on_no_schema: REJECT_BATCH
        # If a record cannot be validated, reject all records in the batch.
        #validation:
          #on_error: REJECT_BATCH

storage:
  provider: GCS
  bucket: "${GCS_BUCKET_NAME}"

iceberg_integration:
  catalogs:
    - name: gcp_iceberg
      bigquery_metastore:
        project: "${GCP_PROJECT_ID}"
        location: "${BQ_LOCATION}"
        cloud_resource_connection: "projects/${GCP_PROJECT_ID}/locations/${BQ_LOCATION}/connections/${BQ_CONNECTION_ID}"
