# see https://akhq.io/docs/configuration/brokers.html
akhq:
  connections:
    bufstream-demo:
      properties:
        bootstrap.servers: "bufstream:9092"
#      schema-registry:
#        url: "https://bufdemo.buf.dev/integrations/confluent/bufstream"
#        type: "confluent"
#        basic-auth-username: "bufstream-demo"
#        basic-auth-password: "316f019d54704848b3055d6c683ec9affad302142e674fa7950367a034969ead"