# yaml-language-server: $schema=schema/buf.bufstream.config.v1alpha1.BufstreamConfig.schema.json
cluster: demo
zone: localhost
in_memory: true
kafka:
  address:
    host: 0.0.0.0
    port: 9092
  public_address:
    host: bufstream
    port: 9092
observability:
  trace_exporter: NONE
  metrics_exporter: NONE
  log_level: INFO
  log_format: TEXT
  debug_address:
    host: 0.0.0.0
#data_enforcement:
#  schema_registries:
#    - name: csr
#      confluent:
#        url: "https://bufdemo.buf.dev/integrations/confluent/bufstream"
#        instance_name: "bufstream"
#        basic_auth:
#          username:
#            string: "bufstream-demo"
#          password:
#            string: "316f019d54704848b3055d6c683ec9affad302142e674fa7950367a034969ead"
#  produce:
#    - topics: { all: true }
#      schema_registry: csr
#      values:
#        on_parse_error: REJECT_BATCH
#        validation:
#          on_error: REJECT_BATCH
#  fetch:
#    - topics: { all: true }
#      schema_registry: csr
#      values:
#        on_parse_error: FILTER_RECORD
#        redaction:
#          debug_redact: true
